### ISSUE TITLE
DB credentials in demo

### ISSUE THREAD

**Issue by heyalexej** [AlJohri/socialscraper#7]
Hey guys. I don't know if this is intended, but you have credentials to your postgres DB in the demo. 

Otherwise, keep up the good work.

**Comment by AlJohri** [comment]
will be taking it down after this 24 hackathon we're working on. thanks @heyalexej 

https://github.com/alpaca/socialscraper/commit/4886870e2dddbae726dab07911d5b504c5d31dc4

**Comment by heyalexej** [comment]
I see. Enjoy hacking and good luck!
